<div class="login">
    <div class="login__content">
        <div class="login__img">
            <img src="assets/img/img-login.svg" alt="">
        </div>

        <div class="login__forms">
            <form action="/auth" method="POST" autocompletye="off" class="login__registre">
                <h1 class="login__title">
                    <b>Entrar</b>
                </h1>

                <?php if (isset($_GET["auth"])) : ?>
                    <span class="text text-danger">E-mail e ou Senha Inválido(s)</span>
                <?php endif; ?>

                <div class="login__box">
                    <i class='bx bx-user login__icon'></i>
                    <input type="text" name="nome" placeholder="Nome de Usuario" class="login__input">
                </div>

                <div class="login__box">
                    <i class='bx bx-lock-alt login__icon'></i>
                    <input type="password" name="senha" placeholder="Senha do Usuario" class="login__input">
                </div>

                <br>

                <button type="submit" class="btn btn-lg btn-success">Entrar</button>
                <a href="/signUp" class="btn btn-lg btn-primary">Inscrever-se</a>
            </form>
        </div>
    </div>
</div>