<div class="login">
    <div class="login__content">
        <div class="login__img">
            <img src="assets/img/img-login.svg" alt="">
        </div>

        <div class="login__forms">
            <form action="/register" method="POST" autocomplete="off" class="login__registre">
                <h1 class="login__title">
                    <b>Inscrever-se</b>
                </h1>

                <div class="login__box">
                    <i class='bx bx-user login__icon'></i>
                    <input type="text" name="nome" placeholder="Nome de Usuario" class="login__input">
                </div>

                <div class="login__box">
                    <i class='bx bx-lock-alt login__icon'></i>
                    <input type="password" name="senha" placeholder="Senha do Usuario" class="login__input">
                </div>

                <br>

                <button type="submit" class="btn btn-lg btn-success">cadastrar</button>
            </form>
        </div>
    </div>
</div>