<div class="card">
    <div class="card-header">
        <div class="row">
            <h2 class="card-title"> &nbsp Consulta de produto</h2>
        </div>
        <div class="card-body">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Produto</th>
                        <th scope="col">Descrição</th>
                        <th scope="col">Preço de Custo</th>
                        <th scope="col">Preço de Venda</th>
                        <th scope="col">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->load->products as $products) : ?>
                        <tr>
                            <th><?= $products["id"] ?></th>

                            <td><?= $products["produto"] ?></td>

                            <td><?= $products["descricao"] ?></td>

                            <th><?= $products["preco_custo"] ?></th>

                            <th><?= $products["preco_venda"] ?></th>

                            <th>
                                <a href="" class="btn btn-danger">Excluir</a>
                                <a href="" class="btn btn-info">Editar</a>
                            </th>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <a href="" class="btn btn-primary">Novo Produto</a>
            <a href="" class="btn btn-primary">Pedidos</a>
        </div>
    </div>
</div>