<!DOCTYPE html>
<html lang="pt-br">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>E-commerce - WebI3</title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

</head>

<body>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

	<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
		<div class="container-fluid">
			<a class="navbar-brand">WEBStore I3</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNavDropdown">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="/store">Home</a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							Clientes
						</a>
						<ul class="dropdown-menu">
							<li><a class="dropdown-item" href="/customerRegistration">Cadastro de Clientes</a></li>
							<li><a class="dropdown-item" href="/customerList">Lista de Clientes</a></li>
						</ul>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							Produtos
						</a>
						<ul class="dropdown-menu">
							<li><a class="dropdown-item" href="" data-bs-toggle="modal" data-bs-target="#productRegister">Cadastro de Produtos</a></li>
							<li><a class="dropdown-item" href="/productList">Lista de Produtos</a></li>
						</ul>
					</li>
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="/leave">Sair</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	<div class="container pt-5">
		<?= $this->content() ?>
	</div>

	<div class="modal fade" id="productRegister" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered">
			<div class="modal-content">
				<div class="modal-header">
					<h1 class="modal-title fs-4" id="exampleModalLabel">Cadastro de Produto</h1>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					<form action="/productRegistration" method="POST" enctype="multipart/form-data" autocomplete="off">
						<div class="mb-2">
							<label for="Produto" class="col-form-label">Produto:</label>
							<input type="text" class="form-control" name="Produto" id="Produto">
						</div>
						<div class="mb-2">
							<label for="Descricao" class="col-form-label">Descrição:</label>
							<textarea class="form-control" name="Descricao" id="Descricao"></textarea>
						</div>
						<div class="mb-2">
							<label for="Preco_Custo" class="col-form-label">Preço de Custo:</label>
							<input type="number" class="form-control" name="Preco_Custo" id="Preco_Custo" min="0" step="0.01">
						</div>
						<div class="mb-3">
							<label for="Preco_Venda" class="col-form-label">Preço de Venda:</label>
							<input type="number" class="form-control" name="Preco_Venda" id="Preco_Venda" min="0" step="0.01">
						</div>
						<div class="form-group">
							<label for="Arquivo">Selecionar um arquivo:</label>
							<input name="Arquivo" id="Arquivo" type="file" class="form-control">
						</div>
						<br>
						<div class="col-lg-12" style="text-align: right;">
							<button type="submit" class="btn btn-success">Salvar</button>
							<button type="button" class="btn btn-danger" data-bs-dismiss="modal">Sair</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</body>

</html>